version: '3.8'

services:
  amu-sport-bot:
    build: .
    container_name: amu_sport_bot
    restart: unless-stopped
    shm_size: '2gb'
    environment:
      - AMU_USER=${AMU_USER}
      - AMU_PASS=${AMU_PASS}
      - TARGET_URL=${TARGET_URL}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}